name: r-mobility-synthetic
gpu: 0
dataset:
  num_chunks: 3335486
  allow_less_chunks: true
  train_ratio: 0.95
  input: /home/hans/leela-training-games/rescored_synthetic_pool/
  train_workers: 3
  test_workers: 2
training:
  precision: half
  swa: true
  swa_output: true
  swa_max_n: 10
  swa_steps: 100
  max_grad_norm: 1.0
  batch_size: 2000
  num_batch_splits: 8
  value_focus_min: 1.0
  value_focus_slope: 0.0
  lookahead_optimizer: false
  renorm: true
  renorm_max_r: 1.0
  renorm_max_d: 0.0
  test_steps: 100
  num_test_positions: 20000
  train_avg_report_steps: 100
  total_steps: 200
  checkpoint_steps: 100
  shuffle_size: 100000
  warmup_steps: 1000
  mask_legal_moves: true
  lr_values:
    - 0.001
    - 0.001
  lr_boundaries:
    - 100
  loss_weights:
    policy: 1.0
    policy_optimistic_st: 0.1
    policy_soft: 8.0
    policy_opponent: 0.1
    policy_next: 0.1
    value_winner: 1.0
    value_q: 1.0
    value_q_cat: 0.1
    value_st: 1.0
    value_q_err: 1.0
    value_st_err: 1.0
    value_st_cat: 0.1
    moves_left: 1.0
    reg: 1.0
    future: 0.1
  path: /home/hans
  optimizer: nadam
  beta_1: 0.9
  beta_2: 0.98
  epsilon: 1.0e-08
  sparse: false
model:
  embedding_size: 512
  policy_embedding_size: 512
  value_embedding_size: 128
  moves_left_embedding_size: 32
  encoder_layers: 10
  encoder_heads: 16
  encoder_d_model: 512
  encoder_dff: 512
  policy_d_model: 512
  policy_d_aux: 512
  dropout_rate: 0.0
  embedding_style: new
  embedding_dense_sz: 64
  value: wdl
  moves_left: v1
  input_type: classic
  use_smolgen: true
  smolgen_hidden_channels: 32
  smolgen_hidden_sz: 256
  smolgen_gen_sz: 256
  smolgen_activation: swish
  omit_qkv_biases: false
  encoder_rms_norm: false
  policy_optimism_strength: 1.0
  n_future_boards: 16
  future: true
  policy_optimistic_st: true
  policy_opponent: false
  policy_next: false
  value_st: true
  value_q: true
  soft_policy: true
  categorical_value_buckets: 32
  soft_policy_temperature: 4.0
