%YAML 1.2
---
name: 'kb1-%filters%x%blocks%-%variant%'
gpu: 0

dataset: 
  num_chunks: %chunks%
  allow_less_chunks: true
  train_ratio: 0.90
  # use a ramdisk for training
  input: '/run/user/1000/merged/'

training:
    batch_size: 1024
    num_batch_splits: 2
    test_steps: 50
    train_avg_report_steps: 50    
    total_steps:  %steps%
    warmup_steps: 250
    shuffle_size: 524288
    lr_values:
    - %lr%
    lr_boundaries:
    - 1000000
    policy_loss_weight: 1.0
    value_loss_weight: 1.0
    path: '%home%'
    moves_left_loss_weight: .01
    value_focus_min: 0.5
    value_focus_slope: 1.0    

model:
  filters: %filters%
  residual_blocks: %blocks%
  se_ratio: 4

  
...
