%YAML 1.2
---
name: 'kb1-64x6-%variant%'
gpu: 0

dataset: 
  num_chunks: %chunks%
  allow_less_chunks: true
  train_ratio: 0.90
  input: '%home%/leela-training-games/%variant%/rescored/*/'

training:
    batch_size: 1024
    test_steps: 5
    train_avg_report_steps: 50
    total_steps:  %steps%
    warmup_steps: 1
    shuffle_size: 524288
    lr_values:
    - %lr%
    lr_boundaries:
    - 1000000
    policy_loss_weight: 1.0
    value_loss_weight: 1.0
    path: '%home%'
    moves_left_loss_weight: .01

model:
  filters: 64
  residual_blocks: 6
  se_ratio: 4

  
...
