%YAML 1.2
---
name: 'kb1-64x6-turbo'
gpu: 0

dataset: 
  num_chunks: 12000
  allow_less_chunks: true
  train_ratio: 0.90
  input: '/mnt/leela-training-games/turbo/lc0/*/'

training:
    batch_size: 1024
    test_steps: 5
    train_avg_report_steps: 50
    total_steps:  250
    warmup_steps: 1
    shuffle_size: 524288
    lr_values:
    - 0.25
    lr_boundaries:
    - 1000000
    policy_loss_weight: 1.0
    value_loss_weight: 1.0
    path: '/mnt'
    moves_left_loss_weight: .01

model:
  filters: 64
  residual_blocks: 6
  se_ratio: 4

  
...
